const pages={Accueil:document.querySelector('#homeView'),Serveurs:document.querySelector('#serversView'),Actualités:document.querySelector('#newsView')};
const breadcrumb=document.querySelector('#breadcrumb'),toast=document.querySelector('#toast');let servers=[],toastTimer,logoClicks=0,logoClickTimer;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function navigate(page){if(!pages[page])return;Object.entries(pages).forEach(([name,section])=>section.hidden=name!==page);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));breadcrumb.textContent=page;history.replaceState(null,'',`#${page.toLowerCase()}`);window.scrollTo({top:0,behavior:'smooth'});}
function renderServers(){const target=document.querySelector('#server-list');if(!servers.length){target.innerHTML='<div class="empty-state">Les informations de Poké\'Nexa sont momentanément indisponibles.</div>';return;}target.innerHTML=servers.map(s=>`<article class="server-card"><div class="server-card-heading"><div class="server-emblem"><img src="/assets/pokenexa-logo.png" alt="Logo Poké'Nexa"></div><div class="server-title"><span class="server-kicker">SERVEUR MINECRAFT</span><h2>${esc(s.name)}</h2><p>Une aventure à vivre ensemble.</p></div><span class="status-pill"><i></i>Statut non vérifié</span></div><div class="server-details"><div class="detail"><span>ADRESSE DU SERVEUR</span><strong>${esc(s.address)}</strong></div><div class="detail"><span>VERSION MINECRAFT</span><strong>${esc(s.version)}</strong></div><div class="detail"><span>LOADER</span><strong>Fabric</strong></div><div class="detail"><span>JOUEURS EN LIGNE</span><strong>—</strong></div></div><div class="server-actions"><button class="primary-button" data-connect="${esc(s.id)}">Copier l'adresse <span>⧉</span></button><a class="download-button" href="${esc(s.downloadUrl)}" download="PokeNexa.zip">Télécharger le modpack <span>↓</span></a><span class="api-note"><i class="api-dot"></i> Archive à importer dans CurseForge · Fabric 0.19.5</span></div></article>`).join('');}
function showToast(m){toast.textContent=m;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2800);}
async function loadServers(){try{const r=await fetch('/api/servers');if(!r.ok)throw Error();servers=(await r.json()).servers;renderServers();}catch{document.querySelector('#server-list').innerHTML='<div class="empty-state">Impossible de charger les informations du serveur pour le moment.</div>';}}
document.querySelectorAll('[data-page],[data-go]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();navigate(el.dataset.page||el.dataset.go);}));
document.addEventListener('click',async e=>{const b=e.target.closest('[data-connect]');if(!b)return;const s=servers.find(x=>x.id===b.dataset.connect);if(!s)return;try{await navigator.clipboard.writeText(s.address);showToast(`Adresse copiée : ${s.address}`);}catch{showToast(`Adresse du serveur : ${s.address}`);}});
const egg=document.querySelector('#easterEgg');document.querySelectorAll('.secret-logo').forEach(img=>img.addEventListener('click',()=>{logoClicks++;clearTimeout(logoClickTimer);if(logoClicks>=5){logoClicks=0;egg.hidden=false;document.querySelector('.easter-close').focus();}else logoClickTimer=setTimeout(()=>logoClicks=0,2500);}));
function closeEgg(){egg.hidden=true;}document.querySelector('.easter-close').addEventListener('click',closeEgg);egg.addEventListener('click',e=>{if(e.target===egg)closeEgg();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!egg.hidden)closeEgg();});
window.addEventListener('hashchange',()=>{const p=Object.keys(pages).find(k=>k.toLowerCase()===location.hash.slice(1));if(p)navigate(p);});
const initial=Object.keys(pages).find(k=>k.toLowerCase()===location.hash.slice(1))||'Accueil';navigate(initial);loadServers();
const events=new EventSource('/api/events');events.addEventListener('servers',e=>{servers=JSON.parse(e.data).servers;renderServers();});
